### ISSUE TITLE
TextField type doesn't propagate properly

### ISSUE THREAD

**Issue by hunterwilliams** [DivertiseAsia/bs-mui#14]
Version: 0.1.34

Summary: The type field doesn't seem to work when using a TextField. The issue is specifically with "password", but assume it affects others as well.

Minimum Code to reproduce

```reasonml
<TextField
          type_="password"
/>
```

which outputs 

```html
<div class="MuiFormControl-root MuiTextField-root" type_="password"><div class="MuiInputBase-root MuiInput-root MuiInput-underline MuiInputBase-formControl MuiInput-formControl"><input aria-invalid="false" type="text" class="MuiInputBase-input MuiInput-input" value=""></div></div>
```

It looks like it tried to put password in, but it never made it to the actual input.

**Comment by hunterwilliams** [comment]
Looks to also affect button

**Comment by alias-r** [comment]
Fix by
https://github.com/DivertiseAsia/bs-mui/commit/628045fd423e78e55b1061728a2cfcdbae656724
