### ISSUE TITLE
Demo Page Online

### ISSUE THREAD

**Issue by hunterwilliams** [DivertiseAsia/bs-mui#2]
Should have a way to view the demo page without downloading/installing. Esp as it's a generated html file already

**Comment by hunterwilliams** [comment]
Proposed solution
1. Create empty gh-pages branch which will house the index.html (similar to the current index.html) and a compiled version of the library. Will just make this branch myself locally and push it up.
2. On release branch commit -> add a separate job to npm-publish.yml called "pages-update". The job will compile a new index.js and commit to the gh-pages branch
3. Will test this out on a separate branch called "release-dummy" to ensure the build part works without having to make a push a new version to npm

If this is fine - I'll proceed, but as it requires a decent amount of configuration and branching want a confirmed go ahead as it won't be done in one pull request.

**Comment by alias-r** [comment]
I think that is great. Please process.

**Comment by hunterwilliams** [comment]
@alias-r Okay I've got this setup to work if you push a commit into release-dummy.  
Two questions
1) Should I add the pages-update as a job in the workflow for npm-publish? Alternative is to have a duplicate workflow as is at the moment which is probably going to not get updated properly going forward.
2) What branch should I make the PR to? master?

**Comment by alias-r** [comment]
It's online now
