### ISSUE TITLE
bs-mui v2.0.0 not working 

### ISSUE THREAD

**Issue by maprangnaveya** [DivertiseAsia/bs-mui#36]
I got this error when I try to use bs-mui v2.0.0 and clean project doesn't help

```
It's possible that your build is stale.
  Try to clean the artifacts and build again?
  Here's the original error message
  The files src/{my_component}.cmi
  and .../node_modules/@divertise-asia/bs-mui/lib/ocaml/materialUI_IconButton.cmi
  make inconsistent assumptions over interface ReactEvent
  
FAILED: cannot make progress due to previous errors.
```
 
my project settings
* react: 16.13.1
* reason-react: 0.9.1

**Comment by alias-r** [comment]
@maprangnaveya can you try remove node and reinstall folder entirely?

**Comment by alias-r** [comment]
Upgraded to react 17 on 2.20. Please try `npx rescript clean && npx rescript build`
