### ISSUE TITLE
JSX2 Compatibility

### ISSUE THREAD

**Issue by hunterwilliams** [DivertiseAsia/bs-mui#4]
All current components should have JSX 2 compatibility

**Comment by puinun1234** [comment]
- [ ] Alert

- [ ] AlertTitle

- [ ] AppBar

- [ ] Autocomplete

- [ ] Avatar

- [ ] AvatarGroup

- [ ] Backdrop

- [ ] Badge

- [ ] BottomNavigation

- [ ] BottomNavigationAction

- [ ] Breadcrums

- [ ] Button

- [ ] ButtonBase

- [ ] ButtonGroup

- [ ] Card

- [ ] CardActionArea

- [ ] CardActions

- [ ] CardContent

- [ ] CardHeader

- [ ] CardMedia

- [ ] Checkbox

- [ ] Chip

- [ ] CircularProgress

- [ ] ClickAwayListener

- [ ] Collapse

- [ ] Container

- [ ] CssBaseline

- [ ] Dialog

- [ ] DialogActions

- [ ] DialogContent

- [ ] DialogContentText

- [ ] DialogTitle

- [ ] Divider

- [ ] Drawer

- [ ] ExpansionPanel

- [ ] ExpansionPanelActions

- [ ] ExpansionPanelDetails

- [ ] ExpansionPanelSummary

- [ ] Fab

- [ ] Fade

- [ ] FilledInput

- [ ] FormControl

- [ ] FormControlLabel

- [ ] FormLabel

- [ ] Grid

- [ ] GridList

- [ ] GridListTile

- [ ] GridListTileBar

- [ ] Grow

- [ ] Hidden

- [ ] Icon

- [ ] IconButton

- [ ] Input

- [ ] InputAdornment

- [ ] InputBase

- [ ] InputLabel

- [ ] LinearProgress

- [ ] Link

- [ ] List

- [ ] ListItem

- [ ] ListItemAvartar

- [ ] ListItemIcon

- [ ] ListItemSecondaryAction

- [ ] ListItemText

- [ ] ListSubHeader

- [ ] Menu

- [ ] MenuItem

- [ ] MenuList

- [ ] MobileStepper

- [ ] Modal

- [ ] NativeSelect

- [ ] NoSsr

- [ ] OutlinedInput

- [ ] Pagination

- [ ] PaginationItem

- [ ] Paper

- [ ] Popover

- [ ] Popper

- [ ] Portal

- [ ] Radio

- [ ] RadioGroup

- [ ] Rating

- [ ] RootRef

- [ ] ScopedCssBaseline

- [ ] Select

- [ ] Skeleton

- [ ] Slide

- [ ] Slider

- [ ] Snacbar

- [ ] SnacbarContent

- [ ] SpeedDial

- [ ] SpeedDialAction

- [ ] SpeedDialIcon

- [ ] Step

- [ ] StepButton

- [ ] StepConnector

- [ ] StepContent

- [ ] StepIcon

- [ ] StebLabel

- [ ] Stepper

- [ ] SvgIcon

- [ ] SwipeableDrawer

- [ ] Switch

- [ ] Tab

- [ ] Table

- [ ] TableBody

- [ ] TableCell

- [ ] TableContainer

- [ ] TableFooter

- [ ] TableHead

- [ ] TablePagination

- [ ] TableRow

- [ ] TableSortLabel

- [ ] Tabs

- [ ] TextareaAutoSize

- [ ] TextField

- [ ] ToggleButton

- [ ] ToggleButtonGroup

- [ ] Toolbar

- [ ] Tooltip

- [ ] TreeItem

- [ ] Treeview

- [ ] Typography

- [ ] Zoom
