### ISSUE TITLE
Issue with JSX2 Component Wrappings

### ISSUE THREAD

**Issue by hunterwilliams** [DivertiseAsia/bs-mui#8]
![image](https://user-images.githubusercontent.com/1759942/77041077-cd405d80-69eb-11ea-8ff8-6e54dc810777.png)
This seems to affect the current master commit of 26e0b25

Yesterday it didn't affect me. Pulled commit f7c29cf (also yesterday) and this bug doesn't exist.

Update --
Bug was introduced in 65e87f6

Note: If you use the last working commit (f7c29cf) and add the below code you get the same error. I'm not certain as to the real cause here.

```
module Popper {
    open MaterialUI.Popper;
    let component = ReasonReact.statelessComponent("Popper");

    let make = (
        ~anchorEl=?,
        ~children,
        ~container=?,
        ~disablePortal=?,
        ~keepMounted=?,
        ~modifiers=?,
        ~_open,
        ~placement=?,
        ~popperOptions=?,
        ~popperRef=?,
        ~transition=?) => 
    ReasonReactCompat.wrapReactForReasonReact(
        make,
        makeProps(
            ~anchorEl?,
            ~children,
            ~container?,
            ~disablePortal?,
            ~keepMounted?,
            ~modifiers?,
            ~_open,
            ~placement?,
            ~popperOptions?,
            ~popperRef?,
            ~transition?,
            ()),
    );   
}
```

**Comment by hunterwilliams** [comment]
Pinpointing culprit

❌ 26e0b25
⌛️ 85a0f933b (testing)
✔️ f7c29cf

**Comment by digitake** [comment]
@puinun1234 @hunterwilliams 
![image](https://user-images.githubusercontent.com/3163988/77055513-9b3af580-6a03-11ea-8d0c-236f10d9686c.png)

**Comment by hunterwilliams** [comment]
@digitake could you post the link to where you took the screenshot? Want to make sure my guess is correct here

**Comment by hunterwilliams** [comment]
https://github.com/marijnh/moduleserve/issues/11 same issue on moduleserve

**Comment by alias-r** [comment]
This is not really an issue of bs-mui itself.
